// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOLpSuWIuhIdt39HRt81OQKN8MqHVphPI',
    appId: '1:562682130544:web:7c7caf73884da52d62c4b5',
    messagingSenderId: '562682130544',
    projectId: 'task-manager-e065c',
    authDomain: 'task-manager-e065c.firebaseapp.com',
    storageBucket: 'task-manager-e065c.firebasestorage.app',
    measurementId: 'G-SNYD02T1VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fa1kS_GaMW79voedXajFk-VDS7QqW04',
    appId: '1:562682130544:android:723a31b3256c7b4162c4b5',
    messagingSenderId: '562682130544',
    projectId: 'task-manager-e065c',
    storageBucket: 'task-manager-e065c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHctvZftbAJsBT4LSa7AzP6zyrbYdVykI',
    appId: '1:562682130544:ios:5c2f3236cfc1820462c4b5',
    messagingSenderId: '562682130544',
    projectId: 'task-manager-e065c',
    storageBucket: 'task-manager-e065c.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHctvZftbAJsBT4LSa7AzP6zyrbYdVykI',
    appId: '1:562682130544:ios:5c2f3236cfc1820462c4b5',
    messagingSenderId: '562682130544',
    projectId: 'task-manager-e065c',
    storageBucket: 'task-manager-e065c.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOLpSuWIuhIdt39HRt81OQKN8MqHVphPI',
    appId: '1:562682130544:web:57174d39cec9656662c4b5',
    messagingSenderId: '562682130544',
    projectId: 'task-manager-e065c',
    authDomain: 'task-manager-e065c.firebaseapp.com',
    storageBucket: 'task-manager-e065c.firebasestorage.app',
    measurementId: 'G-GTYYMM41MG',
  );
}
